name: task_one
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.5.0+1
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  velocity_x: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_gen_runner: ^5.5.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

